### ISSUE TITLE
jcenter()上没有

### ISSUE THREAD

**Issue by jayronlou** [ZhaoKaiQiang/KLog#11]
compile 'com.github.zhaokaiqiang.klog:library:1.1.0'
无法使用

**Comment by ZhaoKaiQiang** [comment]
我这里使用是没有问题的，在jcenter上也可以查找得到，请检查一下你的额项目配置和网络

http://jcenter.bintray.com/com/github/zhaokaiqiang/klog/library/1.1.0/

**Comment by jayronlou** [comment]
恩，可以了，多谢
