### ISSUE TITLE
Constant这个接口的作用是  ？

### ISSUE THREAD

**Issue by bboyfeiyu** [ZhaoKaiQiang/KLog#14]
建议可以将Constant移除，或者将d、e、json等函数提取到一个Logable接口中。

**Comment by ZhaoKaiQiang** [comment]
Constant其实就是为了提供几个公用的常量的，感觉不应该用继承，应该用组合，继承在这里没什么用。抽象出接口来，有相同的打印行为，但是需要的参数不一样，所以不好抽取抽象方法。当然可以用build构建，但是感觉没那个必要。

KLog类可以理解为装饰器模式，对外表现的行为相同，内部其实由不同类组合完成功能。

所以说，项目虽小，但是也用到了组合设计模式、装饰器设计模式，我说的对不对呀，simple哥 @bboyfeiyu 没白看你的大作吧:-D

**Comment by bboyfeiyu** [comment]
@ZhaoKaiQiang 常量还是不要放到Constant接口里的好，既然是常量，为何要继承~   组合并不是组合模式，凯子再好好看看~   :)

**Comment by ZhaoKaiQiang** [comment]
哎呀，组合和继承一样是类之间的关系，我怎么想成设计模式了，走火入魔了
