### ISSUE TITLE
混淆后打印不出log了

### ISSUE THREAD

**Issue by oubowu** [ZhaoKaiQiang/KLog#15]
凯子哥，混淆要怎么配置-_-

**Comment by openproject** [comment]
试试这个
-dontwarn cn.socks.library.**
-keep class cn.socks.library.** { *; }

**Comment by cool-delete** [comment]
加上readme吧 搞了半天才发现引入你这个插件就会发生不能混淆....

**Comment by cool-delete** [comment]
第一次编译不出带混淆的release版本 
后来加上
-ignorewarnings才有/app/build/intermediates/classes-proguard/release/classes.jar
如果在混淆之前编译出release版本 也是可以顺利编译的...但是能不能其作用就不知道了

**Comment by ZhaoKaiQiang** [comment]
最新版本是不需要配置混淆的
