### ISSUE TITLE
华为荣耀手机打不出json

### ISSUE THREAD

**Issue by cxbiao** [ZhaoKaiQiang/KLog#18]
华为荣耀手机打不出json格式的日志！求指教、

**Comment by ZhaoKaiQiang** [comment]
如果打不出JSON，一般都是手机或者是环境问题，原生Log也打不出来

**Comment by cxbiao** [comment]
原生可以，KLog的其他格式也可以！

**Comment by yihaha** [comment]
也遇到打印不出json的问题,原生Log可以打印;示例代码中的json可以打印出,我自己的项目json却打印不出,不知道为什么 ?

**Comment by ZhaoKaiQiang** [comment]
你的json数据是否非常大

**Comment by wangsg** [comment]
log打印不出来，是不是看下手机的log允许输出等级？华为手机或者其他一些手机release版本限制log打印等级

**Comment by lucifdch** [comment]
荣耀手机你需要进入烧录模式，打开调试，这问题之前我也遇到过，所有日志都打印不出来

**Comment by Dev-Wiki** [comment]
华为的日志输出是个坑...

**Comment by ChangSpring** [comment]
华为荣耀P8手机打不出JSON,上面几个可以正常输出,什么情况

**Comment by ZhaoKaiQiang** [comment]
现在手头没有合适的设备进行测试，请问你那边可以解决这个问题吗

**Comment by ZhaoKaiQiang** [comment]
经测试是华为关闭了Debug级别的开关，请打开设备的Log开关再测试

**Comment by ChangSpring** [comment]
[华为手机打开log日志功能](http://kissit.blog.51cto.com/6588582/1154466) 打开华为手机设备的Log开关

**Comment by ZhaoKaiQiang** [comment]
需要打开华为手机的相关Log开关，具体步骤如下：
1.   进入拨号界面输入：*#*#2846579#*#*
2.   依次选择ProjectMenu---后台设置----LOG设置---LOG开关 点击打开, 然后在LOG级别选VERBOSE
3、 重新启动手机
