### ISSUE TITLE
Code links don't work

### ISSUE THREAD

**Issue by mkaflowski** [ZhaoKaiQiang/KLog#20]
I don't get links for code lines. For example (AppAdapter$override.java:47)#OnBindViewHolder ] 3.0 is a just plain text and cannot direct me to the listed line.
I use Android Studio 2.0.

**Comment by l376571926** [comment]
Maybe it just link to Activity(Fragment) or any class extent activity(Fragment).

**Comment by ZhaoKaiQiang** [comment]
I will solve this issue soon , thanks for your suggestion! @mkaflowski

**Comment by ZhaoKaiQiang** [comment]
have been fixed in 1.5.0 version, you can try it @mkaflowski

**Comment by mkaflowski** [comment]
Thank you :)
