### ISSUE TITLE
JsonObject转换带url的json字符串有问题

### ISSUE THREAD

**Issue by 13588823551** [ZhaoKaiQiang/KLog#32]
{\"msg\":\"操作成功\",\"code\":1,\"data\":[{\"id\":21,\"title\":null,\"url\":\"http://www.baidu.com/local/banner/1479782129089.jpg\"}]}
这是原json字符串，
打印出来的url变成了
http:\ /\ /www.baidu.com\ /local\ /banner\ /1479782129089.jpg
请问你能否对转义符做下处理？

**Comment by 13588823551** [comment]
github自动屏蔽转义符，我加了个空格

**Comment by guodongAndroid** [comment]
可以自己在JsonLog.java中这样修改`Log.d(tag, "║ " + line.replaceAll("\\\\", ""));`
就这可以输出正常的url了 @13588823551

**Comment by 13588823551** [comment]
嗯，我已经改好了，忘记关闭问题了，谢谢
