### ISSUE TITLE
功能“支持在Android Studio开发IDE中，点击函数名称，跳转至Log所在位置”无法使用

### ISSUE THREAD

**Issue by LittleWaver** [ZhaoKaiQiang/KLog#36]
功能“支持在Android Studio开发IDE中，点击函数名称，跳转至Log所在位置”无法使用

**Comment by jp1017** [comment]
怎么无法使用,大家都用的好好的, 你的姿势是? @LittleWaver

**Comment by LittleWaver** [comment]
我也是正常使用的，不知道前段时间怎么搞的
打印出来的类名或者方法名，并没有显示可被点击的属性（颜色，下划线）

**Comment by LittleWaver** [comment]
是不是我的AS的Logcat出问题呀，但是我也纳闷问题在什么地方

**Comment by IdioticMadman** [comment]
你是不是没有在对应的project下面看logcat的输出

**Comment by LittleWaver** [comment]
我清理了项目以后就可以了，具体的操作有些模糊。背景就是，AS下的一个项目，开始建了一个module a，后来又把module a拷贝到这个项目重命名为module b，并且后续的开发都是基于module b（两个module里面build.gralde里面的applicationId不同）。后来不知怎么就无法使用功能"点击函数名称就跳转至log打印的所在处"，这两天进行项目清理的时候，删除了前期开发的module a等，突然不知为何这个功能又可以使用了。
