### ISSUE TITLE
关于统一开关的问题

### ISSUE THREAD

**Issue by xk009** [ZhaoKaiQiang/KLog#4]
经常会有这样的需求，release版本的时候，需要把log禁用。但是要是 代码中到处充斥着 
``` if （logEnabled） {
   KLog.d();
} ```
不那么优雅。是不是可以一个在KLOG中提供一个统一的开关，eg:  KLOG.setEnable();

**Comment by ZhaoKaiQiang** [comment]
可以参考我的中文文档，可以使用KLog.init(false)来实现全局开关，在README.MD里面

**Comment by xk009** [comment]
> 可以参考我的中文文档，可以使用KLog.init(false)来实现全局开关，在README.MD里面

Thanks ! I find it in the same time.
