### ISSUE TITLE
打印json只能读取前4000个左右字节

### ISSUE THREAD

**Issue by jp1017** [ZhaoKaiQiang/KLog#5]
我获取的json较大，后面的部分数据不显示。

当我设置JSON_INDENT = 0时，显示正常。

这个问题在Logger下正常，他可以打印任意长度json数据。

**Comment by jp1017** [comment]
这里有个json供测试

{"Param1":2,"Param2":"linux","Param3":[0,3,4,0,0,0,2,0,4,4,0,0,0,120,0,2,4,0,0,0,20,0,69,4,0,0,0,1,0,71,4,0,0,48,57,0,70,4,0,0,1,44,0,64,11,49,51,49,53,54,53,49,54,56,49,0,0,64,10,49,50,51,52,53,54,55,56,57,0,0,64,10,57,56,55,54,53,52,51,50,49,0,0,64,7,49,53,57,55,53,51,0,0,68,9,50,51,53,51,52,54,51,52,0,0,68,8,51,52,54,52,48,57,56,0,0,68,8,50,53,52,51,54,48,57,0,0,83,4,31,255,255,159,0,80,4,31,255,255,231,0,148,6,66,84,48,49,50,51,0,146,13,50,48,49,53,48,52,49,53,54,56,52,56,0],"Param4":"晋文公我见过我感觉为佛","Param5":"15646999999","Param6":1,"Param7":23,"Reason":"OK","VehiclePlate":"鲁BT0123"}

**Comment by ZhaoKaiQiang** [comment]
多谢，下个版本我会修复这个BUG

**Comment by ZhaoKaiQiang** [comment]
我测试了下，给出的这个字符串可以正常打印

**Comment by jp1017** [comment]
用库就可以打印吗？
我设置JSON_INDENT 为0时才可以打印，用你的库少后面的一部分，库里面的JSON_INDENT 值为4。

**Comment by ZhaoKaiQiang** [comment]
后面的那部分在最前面吧，顺序不一样

**Comment by jp1017** [comment]
我这里测试后面打印不出来，你可以把上面json数据Param3数据增加一些测试下，下面是我测试结果：

![test](http://7xlah4.com1.z0.glb.clouddn.com/20151118084656.png)

Param4后面都打印不出来。

**Comment by ZhaoKaiQiang** [comment]
最新版本已修复，你可以再测试下，这次支持任意长度JSON数据

**Comment by jp1017** [comment]
可以了，非常感谢！

**Comment by ZhaoKaiQiang** [comment]
客气^_^
