### ISSUE TITLE
最新版1.1.0，Klog.d 等打印字符串只能前4000个左右

### ISSUE THREAD

**Issue by jp1017** [ZhaoKaiQiang/KLog#9]
如题，找个文章打印下

**Comment by ZhaoKaiQiang** [comment]
原生Log.d()对打印长度也是有限制的，对于非json和xml格式的普通字符串，打印长度也是有限制的，一个解决方案是将打印字符串拆解，分次打印

**Comment by jp1017** [comment]
原来如此，测试了原生打印，也是4000多个字符，谢谢！

**Comment by guduey** [comment]
android studio 真机调试，Klog.d 看不到信息。。。

**Comment by ZhaoKaiQiang** [comment]
Klog使用的也是原生Log，你使用Log测试下，看看是否可以打印出来

**Comment by guduey** [comment]
啊呀，原生也不打印，我换手机试下。。。

**Comment by ZhaoKaiQiang** [comment]
下个版本会增加对无限长字符串的支持

**Comment by passos** [comment]
adb logcat -g

**Comment by ZhaoKaiQiang** [comment]
thanks you ,l will fix this issue next version ! @passos

**Comment by ZhaoKaiQiang** [comment]
this issue have been fixed at version 1.2.0
